Repository AegisLenz/AegisLenz-BE, pull requests merged in 2024-10, with the labels that each got.

#8 Feat/#6
  .gitignore
  ai/model_loader.py
  ai/predict.py
  main.py
  requirements.txt
  routers/bert_router.py
  schemas/bert_schema.py
  services/bert_service.py
Labels: 💫 feature

#7 Feat/#5
  core/redis_driver.py
  main.py
  requirements.txt
  routers/prompt_router.py
  schemas/prompt_schema.py
  services/prompt_service.py
  utils/chatgpt.py
  utils/prompt.txt
Labels: 💫 feature

#13 Infra/#9
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
Labels: 🗃️ infra

#14 Fix: docker-compose.yml 파일 수정 (#9)
  docker-compose.yml
Labels: 🐛 bug, 🗃️ infra

#16 Infra/#9
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: 🐛 bug, 🗃️ infra, ♻️ refactor

#18 Fix: docker-compose stop/start -> down/up으로 변경 (#9)
  .github/workflows/deploy.yml
Labels: 🐛 bug, 🗃️ infra

#20 Setting/#15
  core/logging_config.py
  core/mongodb_driver.py
  docker-compose.yml
  main.py
  models/user_model.py
  repositories/user_repository.py
  requirements.txt
  routers/user_router.py
  services/user_service.py
Labels: 🗃️ infra, ⚙️ setting

#21 Setting/#15
  docker-compose.yml
Labels: 🐛 bug, 🗃️ infra

#19 Test/#17
  getIAM/getConnection.py
  getIAM/getEC2.py
  getIAM/getIAM.py
  getIAM/getS3.py
Labels: ✅ test

#24 Feat/#11
  docker-compose.yml
  routers/bert_router.py
Labels: 💫 feature
