Repository AegisLenz/AegisLenz-BE, pull requests merged in 2024-11, with the labels that each got.

#26 Feat/#25
  getIAM/getConnection.py
  getIAM/getEC2.py
  getIAM/getIAM.py
  getIAM/getS3.py
  getResource/getEC2.py
  getResource/getIAM.py
  getResource/getS3.py
  getResource/insertDB.py
  models/asset_model.py
Labels: 💫 feature

#32 Fix/#31
  getAsset/getIAM.py
  models/asset_model.py
Labels: 🐛 bug

#30 Feat/#23
  core/mongodb_driver.py
  models/prompt_model.py
  repositories/prompt_repository.py
  routers/prompt_router.py
  schemas/prompt_schema.py
  services/prompt_service.py
  services/prompts/ClassifyPr.txt
  services/prompts/DetailPr.txt
  services/prompts/onlyES.txt
  services/prompts/onlyMDB.txt
  services/prompts/policy.txt
  utils/chatgpt.py
Labels: 💫 feature

#33 Remove: Dashboard 파일 삭제 (#23)
  services/prompt_service.py
Labels: 🐛 bug

#36 Fix: iam-policy 경로 설정 수정 (#34)
  utils/insert_initial_data.py
Labels: 🐛 bug

#37 Fix: submodule도 가져오도록 설정 (#34)
  .github/workflows/deploy.yml
Labels: 🐛 bug

#39 Fix: submodule도 가져오도록 설정 (#34)
  .github/workflows/deploy.yml
Labels: 🐛 bug

#42 Fix: Summary 페르소나에 초기화 프롬프트 텍스트 추가 (#41)
  services/prompt_service.py
Labels: 🐛 bug

#48 Feat: 정책 세부내용 저장 (#47)
  getAsset/getIAM.py
  models/asset_model.py
  repositories/user_repository.py
  services/user_service.py
Labels: 💫 feature

#52 Hotfix/#46
  core/redis_driver.py
  routers/bert_router.py
Labels: 💫 feature, ♻️ refactor

#53 Feat/#51
  models/attack_detection_model.py
  repositories/bert_repository.py
  repositories/prompt_repository.py
  routers/bert_router.py
  schemas/prompt_schema.py
  services/bert_service.py
  services/prompt_service.py
  utils/policy/filter_original_policy.py
Labels: 💫 feature

#55 Feat/#54
  routers/bert_router.py
  schemas/bert_schema.py
  services/bert_service.py
Labels: 💫 feature

#58 Hotfix/#56
  services/prompt_service.py
Labels: 🐛 bug

#66 Fix/#62
  .gitmodules
Labels: 🐛 bug

#65 Feat/#63
  services/policy/common_utils.py
Labels: 💫 feature
