Repository AegisLenz/AegisLenz-BE, pull requests merged in 2024-12, with the labels that each got.

#71 Feat/#70
  common/elasticsearch_mapping.json
  common/tactics_mapping.json
  routers/bert_router.py
Labels: 💫 feature

#73 Feat/#72
  models/user_model.py
  repositories/user_repository.py
  routers/user_router.py
  schemas/user_schema.py
  services/user_service.py
Labels: 💫 feature

#78 Setting/#77
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.override.yml
  docker-compose.prod.yml
Labels: 🗃️ infra

#83 Feat/#69
  main.py
  models/asset_model.py
  models/attack_detection_model.py
  models/policy_model.py
  models/prompt_model.py
  repositories/asset_repository.py
  repositories/bert_repository.py
  requirements.txt
  routers/dashboard_router.py
  schemas/dashboard_schema.py
  services/asset/get_ec2.py
  services/asset/get_iam.py
  services/asset/get_s3.py
  services/asset_service.py
  services/dashboard_service.py
  services/gpt_service.py
  services/policy/comparePolicy.py
  services/policy/filter_original_policy.py
  services/policy_service.py
  services/prompt_service.py
Labels: 💫 feature

#85 Hotfix: 대시보드 및 자산 관련 에러 해결 (#84)
  repositories/bert_repository.py
  repositories/user_repository.py
  services/dashboard_service.py
Labels: 🐛 bug

#82 Feat/#81
  database/redis_driver.py
  main.py
  requirements.txt
  routers/bert_router.py
  services/es_service.py
Labels: 💫 feature, ♻️ refactor

#90 Feat/#75
  models/prompt_model.py
  repositories/bert_repository.py
  repositories/prompt_repository.py
  routers/prompt_router.py
  schemas/prompt_schema.py
  services/bert_service.py
  services/dashboard_service.py
  services/prompt/query_parser.py
  services/prompt_service.py
  t.json
Labels: 💫 feature

#92 Refactor/#91
  models/user_model.py
  repositories/user_repository.py
  routers/user_router.py
  schemas/user_schema.py
  services/user_service.py
Labels: ♻️ refactor

#80 Feat/#79
  services/policy/comparePolicy.py
  services/policy/ec2_policy_mapper.py
  services/policy/extract_policy_by_cloudTrail.py
Labels: 💫 feature

#94 Feat/#93
  repositories/prompt_repository.py
  schemas/dashboard_schema.py
  services/dashboard_service.py
Labels: 💫 feature

#99 Feat/#86
  models/attack_detection_model.py
  repositories/bert_repository.py
  repositories/report_repository.py
  routers/report_router.py
  schemas/report_schema.py
  services/bert_service.py
  services/gpt_service.py
  services/report_service.py
Labels: 💫 feature

#101 Refactor/#100
  models/user_model.py
  repositories/dashboard_repository.py
  repositories/prompt_repository.py
  repositories/user_repository.py
  services/bert_service.py
  services/dashboard/daily_insight.py
  services/dashboard_service.py
  services/gpt_service.py
  services/prompt_service.py
Labels: ♻️ refactor

#103 Feat/#89
  common/tactics_mapping.json
  database/redis_driver.py
  main.py
  routers/bert_router.py
  services/es_service.py
Labels: 💫 feature, ♻️ refactor

#110 Feat/#105
  repositories/user_repository.py
  services/policy/common_utils.py
  services/policy/comparePolicy.py
  services/policy/extract_policy_by_cloudTrail.py
  services/policy/service_filtering.py
  services/policy_service.py
Labels: 💫 feature

#112 Feat: BERT 결과 실시간 초리 로직 개선 (#111)
  database/redis_driver.py
  routers/bert_router.py
  services/es_service.py
Labels: 💫 feature

#118 Fix: Redis 큐잉 버퍼 처리 로직 변경 (#117)
  database/redis_driver.py
  routers/bert_router.py
Labels: 💫 feature

#121 Fix: SSE 이벤트 로직 변경 (#117)
  routers/bert_router.py
Labels: 💫 feature

#122 Fix: BertRouter 일부 로직 개선 (#117)
  routers/bert_router.py
Labels: 💫 feature

#123 Fix: 마지막 예외처리 로그 추가 (#117)
  routers/bert_router.py
Labels: 💫 feature
